version: '3.7'

x-container-common:
  &container-common
  restart: ${CONTAINER_RESTART-on-failure}
  networks:
    - qkm

x-postgres-common:
  &postgres-common
  environment:
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}

services:
  postgres-ssl-init:
    image: gcr.io/distroless/static:debug
    volumes:
      - ./postgres/tls/tls.key:/server.key:ro
      - postgres-key:/postgres-key
    entrypoint:
      - sh
      - -c
      - |
        cp /server.key /postgres-key/server.key
        chown 70 /postgres-key/server.key
        chmod 0600 /postgres-key/server.key

  postgres-ssl:
    <<: [ *container-common, *postgres-common ]
    image: postgres:13.11-alpine
    # command: ["postgres", "-c", "max_connections=100"]
    # command: ["postgres", "-c", "log_statement=all"]
    command: >
      -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/key/server.key -c ssl_ca_file=/var/lib/postgresql/ca.crt
    volumes:
      - db-data-api:/var/lib/postgresql/data
      - ./postgres/tls/tls.crt:/var/lib/postgresql/server.crt:ro
      - postgres-key:/var/lib/postgresql/key:ro
      - ./postgres/tls/ca.crt:/var/lib/postgresql/ca.crt:ro
    ports:
      - 5432
    depends_on:
      - postgres-ssl-init

  postgres:
    <<: [ *container-common, *postgres-common ]
    image: postgres:13.11-alpine
    # command: ["postgres", "-c", "max_connections=100"]
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - db-data-api:/var/lib/postgresql/data
    ports:
      - 5432

volumes:
  db-data-api:
    driver: local
  postgres-key:
    driver: local

networks:
  qkm:
    driver: bridge
