version: '3.7'

x-container-common:
  &container-common
  restart: ${CONTAINER_RESTART-on-failure}
  networks:
    - qkm

services:
  geth:
    <<: *container-common
    image: ethereum/client-go:v1.10.9
    entrypoint:
      - /bin/sh
      - -c
      - |
        geth --datadir "/nodeData" init "/nodeData/genesis.json"
        geth \
        --http \
        --http.addr "0.0.0.0" \
        --http.port "${GETH_RPC_PORT-8545}" \
        --http.api "admin,eth,net,web3,personal,txpool" \
        --http.corsdomain "*" \
        --http.vhosts "*" \
        --datadir "/nodeData" \
        --port "${GETH_PORT-30303}" \
        --networkid ${GETH_NETWORKID-888} \
        --nodiscover \
        --unlock "0" \
        --password "/nodeData/password" \
        --allow-insecure-unlock \
        --mine \
        --ipcdisable \
        --syncmode "full"
    volumes:
      - ./config/genesis.json:/nodeData/genesis.json
      - ./config/keystore:/nodeData/keystore
      - ./config/password:/nodeData/password
      - chain-data:/nodeData/geth
    ports:
      - 8546:8545
    networks:
      - qkm
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "--proxy",
          "off",
          "http://localhost:8545"
        ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s

volumes:
  chain-data:
    driver: local

networks:
  qkm:
    external: true
    name: deps_qkm
